## 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[10,11,12],
        [13,14,15],
        [16,17,18]])

Matsum = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,Matsum))

The Sum of two matrix 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  and 

[[10 11 12]
 [13 14 15]
 [16 17 18]]  is 

[[11 13 15]
 [17 19 21]
 [23 25 27]] 


## 2. Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np

mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[10,11,12],
        [13,14,15],
        [16,17,18]])


Math_multi = np.dot(mat1,mat2)

print("The Multiply of two matrix   \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,Math_multi))

The Multiply of two matrix   

[[1 2 3]
 [4 5 6]
 [7 8 9]]  and 

[[10 11 12]
 [13 14 15]
 [16 17 18]]  is 

[[ 84  90  96]
 [201 216 231]
 [318 342 366]] 


## 3. Write a Python Program to Transpose a Matrix?

In [3]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[1,2],[4,5],[7,8]]
c = [[1,2,3],[4,5,6]]

def generate_transpose(in_matrix):
    out_matrix = []
    for ele in range(len(in_matrix[0])):
        out_matrix.append([0 for i in range(len(in_matrix))])
    for i in range(len(in_matrix)):
        for j in range(len(in_matrix[i])):
            out_matrix[j][i] = in_matrix[i][j]
    print(f'{in_matrix} -> {out_matrix}')
        
generate_transpose(a)
generate_transpose(b)
generate_transpose(c)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]] -> [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
[[1, 2], [4, 5], [7, 8]] -> [[1, 4, 7], [2, 5, 8]]
[[1, 2, 3], [4, 5, 6]] -> [[1, 4], [2, 5], [3, 6]]


## 4. Write a Python Program to Sort Words in Alphabetic Order? 

In [5]:
def sortString():
    in_string = input("Enter a String: ").title()
    sorted_list = sorted(in_string.split(' '))
    print(' '.join(sorted_list))

sortString()

Enter a String: Data Science master 2.0
2.0 Data Master Science


## 5. Write a Python Program to Remove Punctuation From a String?

In [8]:
def removePunctuatuions():
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    in_string = input('Enter a String: ')
    out_string = ''
    for ele in in_string:
        if ele not in punctuations:
            out_string += ele
    print(out_string)
    
removePunctuatuions()

Enter a String: Lets fight !@#$%^&*()_ together 
Lets fight  together 
